version: '3.8'

services:
  app:
    image: ghcr.io/mightynerd/hit:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PG_CONNECTION_STRING: "postgres://user:${POSTGRES_PASSWORD}@db:5432/hit?sslmode=disable"
      SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID}"
      SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
      SERVICE_URL: "${SERVICE_URL:-http://localhost:8080}"
      DISCOGS_API_KEY: "${DISCOGS_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      GIN_MODE: "release"
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "hit"
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_data: